/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad29;

import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class cafeteria extends javax.swing.JFrame {
    int precio;
    int resultado=0;
    int persona=0;
 
    /**
     * Creates new form cafeteria
     */
    public cafeteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chbm = new javax.swing.JCheckBox();
        chbg = new javax.swing.JCheckBox();
        chba = new javax.swing.JCheckBox();
        chbe = new javax.swing.JCheckBox();
        chbc = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chbcrema = new javax.swing.JCheckBox();
        chbchispas = new javax.swing.JCheckBox();
        chbcc = new javax.swing.JCheckBox();
        chbl = new javax.swing.JCheckBox();
        chbb = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtresultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chbpay = new javax.swing.JCheckBox();
        chbpas = new javax.swing.JCheckBox();
        chbflan = new javax.swing.JCheckBox();
        chbcarlota = new javax.swing.JCheckBox();
        chbga = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtu = new javax.swing.JTextField();
        txtu2 = new javax.swing.JTextField();
        btnpedido = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnpagar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtp2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Cafeteria el dicho");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel3.setText("Cafe");

        chbm.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbm.setText("Mediano = $25");
        chbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbmActionPerformed(evt);
            }
        });

        chbg.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbg.setText("Grande = $35");

        chba.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chba.setText("Americano = 78");

        chbe.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbe.setText("Expresso = 60");

        chbc.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbc.setText("Chico = $15");
        chbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chbm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(chbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(chbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chba)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel4.setText("Extras cafe");

        chbcrema.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbcrema.setText("crema = $3");

        chbchispas.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbchispas.setText("Chispas chococaltes = $5");

        chbcc.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbcc.setText("Chispas colores = $5");

        chbl.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbl.setText("Leche = $10");

        chbb.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbb.setText("Crema batida = $20");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chbchispas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbcrema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbcrema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbchispas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel5.setText("Unidades");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel6.setText("Total a pagar");

        txtresultado.setEditable(false);
        txtresultado.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel7.setText("Postres");

        chbpay.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbpay.setText("Pay de queso = $35");

        chbpas.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbpas.setText("Pastel de vainilla = $25");

        chbflan.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbflan.setText("Flan = $20");

        chbcarlota.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbcarlota.setText("Carlota de limon = $55");

        chbga.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        chbga.setText("Galletas = $15");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chbflan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbpas, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addComponent(chbpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbcarlota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chbga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbpay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbpas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbflan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbcarlota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel8.setText("Unidades");

        txtu.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        txtu2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        btnpedido.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        btnpedido.setText("Hacer pedido");
        btnpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpedidoActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnpagar.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        btnpagar.setText("Pagar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel9.setText("NO.Pedidos");

        txtp2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        txtp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel9)
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(165, 165, 165))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnpagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnpedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(94, 94, 94))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtu)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtu2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtu2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnpedido)
                                .addGap(18, 18, 18)
                                .addComponent(btnreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpagar)))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbmActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultadoActionPerformed

    private void btnpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpedidoActionPerformed

 if(!txtu.getText().isEmpty()&&!txtu.getText().isEmpty()){
     
        if(chbc.isSelected()||chbm.isSelected()||chbg.isSelected()||chbe.isSelected()||chba.isSelected()){
               persona=Integer.parseInt(txtp2.getText());
               persona++;
               txtp2.setText(String.valueOf(persona));
 }
        if(chbc.isSelected()){  
    JOptionPane.showMessageDialog(null,"Seleccionaste cafe chico");
       

            precio=precio+15;
}         
         if(chbm.isSelected()){
                JOptionPane.showMessageDialog(null,"Seleccionaste cafe Medio");

             precio=precio+25;

         }
          if(chbg.isSelected()){
              JOptionPane.showMessageDialog(null,"Seleccionaste cafe grande");

             precio=precio+35;
         }
           if(chbe.isSelected()){
               JOptionPane.showMessageDialog(null,"Seleccionaste cafe expreso");

             precio=precio+60;

         }
            if(chba.isSelected()){
               JOptionPane.showMessageDialog(null,"Seleccionaste cafe americano");

             precio=precio+78;

         }
             if(chbcrema.isSelected()){
              JOptionPane.showMessageDialog(null,"Seleccionaste ponerle crema");

             precio=precio+3;

         }
              if(chbchispas.isSelected()){
              JOptionPane.showMessageDialog(null,"Seleccionaste ponerle chispas de chocolate");

             precio=precio+5;

         }
               if(chbcc.isSelected()){
              JOptionPane.showMessageDialog(null,"Seleccionaste ponerle chispas de colores");

             precio=precio+5;

         }
                if(chbl.isSelected()){
               JOptionPane.showMessageDialog(null,"Seleccionaste pornerle lehe al cafe");

             precio=precio+10;

         }
                   if(chbb.isSelected()){
             JOptionPane.showMessageDialog(null,"Seleccionaste ponerle crema batida");
               
             precio=precio+20;

         } 
                   if(!txtu2.getText().isEmpty()){
                  if(chbga.isSelected()||chbpay.isSelected()||chbpas.isSelected()||chbflan.isSelected()||chbcarlota.isSelected()){
                      JOptionPane.showMessageDialog(null,"postres seleccionados: ");

                   }
                       

                        if(chbga.isSelected()){
                       JOptionPane.showMessageDialog(null,"galletas");

             precio=precio+15;

         }
                             if(chbpay.isSelected()){
                     JOptionPane.showMessageDialog(null,"pay de queso");

             precio=precio+35;

         }
                                  if(chbpas.isSelected()){
                       JOptionPane.showMessageDialog(null,"pastel");

             precio=precio+25;

         }
                                       if(chbflan.isSelected()){
              JOptionPane.showMessageDialog(null,"Seleccionaste flan");

             precio=precio+20;

         }
                                            if(chbcarlota.isSelected()){
                  JOptionPane.showMessageDialog(null,"carlota de limon");

             precio=precio+55;

               }    
                                             if(txtu2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Selecciona las unidades de postre");
        }
                   }
             
               resultado=precio;
         }
 if(!chbc.isSelected()&&!chbm.isSelected()&&!chbg.isSelected()&&!chbe.isSelected()&&!chba.isSelected()){
                JOptionPane.showMessageDialog(null,"no a seleccionado ningun cafe");
              
        }
 if(!chbga.isSelected()&&!chbpay.isSelected()&&!chbpas.isSelected()&&!chbflan.isSelected()&&!chbcarlota.isSelected()){
                JOptionPane.showMessageDialog(null,"no a seleccionado ningun postre");
              
        }
        if(txtu.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Selecciona las unidades");
        }
        
    }//GEN-LAST:event_btnpedidoActionPerformed

    
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtu.setText("");
         txtu2.setText("");
        chbc.setSelected(false);
        chbm.setSelected(false);
        chbg.setSelected(false);
        chbe.setSelected(false);
        chba.setSelected(false);
        chbcrema.setSelected(false);
        chbchispas.setSelected(false);
        chbcc.setSelected(false);
        chbl.setSelected(false);
        chbb.setSelected(false);
        chbga.setSelected(false);
        chbpay.setSelected(false);
        chbpas.setSelected(false);
        chbflan.setSelected(false);
        chbcarlota.setSelected(false);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
          if(persona!=0){
              persona=persona-1;
              txtresultado.setText(String.valueOf(resultado));
             JOptionPane.showMessageDialog(null,"pago exitoso");
             JOptionPane.showMessageDialog(null,"gracias por venir :)");
             System.exit(0); 
          }else{
               JOptionPane.showMessageDialog(null,"no se ha hecho ningun pedido");

          }  
            
         
       
       
       
    }//GEN-LAST:event_btnpagarActionPerformed

    private void txtp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtp2ActionPerformed
        

    }//GEN-LAST:event_txtp2ActionPerformed

    private void chbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafeteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpagar;
    private javax.swing.JButton btnpedido;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox chba;
    private javax.swing.JCheckBox chbb;
    private javax.swing.JCheckBox chbc;
    private javax.swing.JCheckBox chbcarlota;
    private javax.swing.JCheckBox chbcc;
    private javax.swing.JCheckBox chbchispas;
    private javax.swing.JCheckBox chbcrema;
    private javax.swing.JCheckBox chbe;
    private javax.swing.JCheckBox chbflan;
    private javax.swing.JCheckBox chbg;
    private javax.swing.JCheckBox chbga;
    private javax.swing.JCheckBox chbl;
    private javax.swing.JCheckBox chbm;
    private javax.swing.JCheckBox chbpas;
    private javax.swing.JCheckBox chbpay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtp2;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JTextField txtu;
    private javax.swing.JTextField txtu2;
    // End of variables declaration//GEN-END:variables
}
